# Generated by Django 4.2.11 on 2026-07-02 07:50

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cartographie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('date_deces', models.DateField()),
                ('lieu_deces', models.CharField(blank=True, max_length=200)),
                ('nationalite', models.CharField(blank=True, max_length=100)),
                ('acte_deces_numero', models.CharField(blank=True, max_length=100, verbose_name='N° acte de décès')),
                ('acte_deces_fichier', models.FileField(blank=True, null=True, upload_to='documents/actes_deces/', verbose_name='Acte de décès (scan)')),
            ],
            options={
                'verbose_name': 'Défunt',
                'verbose_name_plural': 'Défunts',
                'ordering': ['-date_deces'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalReservation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('numero_dossier', models.CharField(db_index=True, max_length=20, verbose_name='N° dossier')),
                ('statut', models.CharField(choices=[('ATTENTE', 'En attente de validation'), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée'), ('ANNULEE', 'Annulée')], default='ATTENTE', max_length=10)),
                ('date_soumission', models.DateTimeField(blank=True, editable=False)),
                ('date_inhumation_souhaitee', models.DateField(blank=True, null=True, verbose_name="Date d'inhumation souhaitée")),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('motif_rejet', models.TextField(blank=True)),
                ('notes_admin', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Réservation',
                'verbose_name_plural': 'historical Réservations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_dossier', models.CharField(max_length=20, unique=True, verbose_name='N° dossier')),
                ('statut', models.CharField(choices=[('ATTENTE', 'En attente de validation'), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée'), ('ANNULEE', 'Annulée')], default='ATTENTE', max_length=10)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_inhumation_souhaitee', models.DateField(blank=True, null=True, verbose_name="Date d'inhumation souhaitée")),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('motif_rejet', models.TextField(blank=True)),
                ('notes_admin', models.TextField(blank=True)),
                ('caveau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='cartographie.caveau')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-date_soumission'],
            },
        ),
    ]
