# Generated by Django 4.2.11 on 2026-07-02 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cartographie', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='client',
            field=models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='defunt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reservation', to='reservations.defunt'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='validee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_validees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalreservation',
            name='caveau',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cartographie.caveau'),
        ),
        migrations.AddField(
            model_name='historicalreservation',
            name='client',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'role': 'CLIENT'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalreservation',
            name='defunt',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='reservations.defunt'),
        ),
        migrations.AddField(
            model_name='historicalreservation',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalreservation',
            name='validee_par',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
