# Generated by Django 4.2.11 on 2026-07-02 07:50

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(max_length=20, unique=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EMISE', 'Émise'), ('PARTIEL', 'Partiellement payée'), ('PAYEE', 'Payée'), ('ANNULEE', 'Annulée'), ('RETARD', 'En retard')], default='BROUILLON', max_length=10)),
                ('sous_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('tva_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('montant_tva', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('montant_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('montant_paye', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('date_emission', models.DateTimeField(auto_now_add=True)),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('pdf_fichier', models.FileField(blank=True, null=True, upload_to='documents/factures/')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-date_emission'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalFacture',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('numero_facture', models.CharField(db_index=True, max_length=20)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EMISE', 'Émise'), ('PARTIEL', 'Partiellement payée'), ('PAYEE', 'Payée'), ('ANNULEE', 'Annulée'), ('RETARD', 'En retard')], default='BROUILLON', max_length=10)),
                ('sous_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('tva_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('montant_tva', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('montant_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('montant_paye', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('date_emission', models.DateTimeField(blank=True, editable=False)),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('pdf_fichier', models.TextField(blank=True, max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Facture',
                'verbose_name_plural': 'historical Factures',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPaiement',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('canal', models.CharField(choices=[('MOBILE_MONEY', 'Mobile Money (MTN)'), ('AIRTEL_MONEY', 'Airtel Money'), ('ESPECES', 'Espèces'), ('VIREMENT', 'Virement bancaire'), ('CHEQUE', 'Chèque')], max_length=15)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('reference_transaction', models.CharField(blank=True, max_length=100)),
                ('telephone_paiement', models.CharField(blank=True, max_length=20)),
                ('date_paiement', models.DateTimeField(blank=True, editable=False)),
                ('notes', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Paiement',
                'verbose_name_plural': 'historical Paiements',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTarif',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('type_tarif', models.CharField(choices=[('TEMP_5', 'Concession temporaire 5 ans'), ('TEMP_10', 'Concession temporaire 10 ans'), ('TEMP_15', 'Concession temporaire 15 ans'), ('PERP', 'Concession perpétuelle'), ('FAM', 'Concession familiale'), ('RENOUV', 'Renouvellement'), ('EXHUM', "Autorisation d'exhumation"), ('DOSSIER', 'Frais de dossier'), ('ENTRET', 'Entretien')], db_index=True, max_length=10)),
                ('montant_fcfa', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_modification', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Tarif',
                'verbose_name_plural': 'historical Tarifs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('type_tarif', models.CharField(blank=True, choices=[('TEMP_5', 'Concession temporaire 5 ans'), ('TEMP_10', 'Concession temporaire 10 ans'), ('TEMP_15', 'Concession temporaire 15 ans'), ('PERP', 'Concession perpétuelle'), ('FAM', 'Concession familiale'), ('RENOUV', 'Renouvellement'), ('EXHUM', "Autorisation d'exhumation"), ('DOSSIER', 'Frais de dossier'), ('ENTRET', 'Entretien')], max_length=10)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Ligne de facture',
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('MOBILE_MONEY', 'Mobile Money (MTN)'), ('AIRTEL_MONEY', 'Airtel Money'), ('ESPECES', 'Espèces'), ('VIREMENT', 'Virement bancaire'), ('CHEQUE', 'Chèque')], max_length=15)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('reference_transaction', models.CharField(blank=True, max_length=100)),
                ('telephone_paiement', models.CharField(blank=True, max_length=20)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_tarif', models.CharField(choices=[('TEMP_5', 'Concession temporaire 5 ans'), ('TEMP_10', 'Concession temporaire 10 ans'), ('TEMP_15', 'Concession temporaire 15 ans'), ('PERP', 'Concession perpétuelle'), ('FAM', 'Concession familiale'), ('RENOUV', 'Renouvellement'), ('EXHUM', "Autorisation d'exhumation"), ('DOSSIER', 'Frais de dossier'), ('ENTRET', 'Entretien')], max_length=10, unique=True)),
                ('montant_fcfa', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tarif',
                'verbose_name_plural': 'Tarifs',
            },
        ),
        migrations.CreateModel(
            name='TransactionMobileMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=30, unique=True, verbose_name='Référence transaction')),
                ('canal', models.CharField(choices=[('MOBILE_MONEY', 'Mobile Money (MTN)'), ('AIRTEL_MONEY', 'Airtel Money'), ('ESPECES', 'Espèces'), ('VIREMENT', 'Virement bancaire'), ('CHEQUE', 'Chèque')], max_length=15)),
                ('telephone', models.CharField(max_length=20, verbose_name='Numéro Mobile Money')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('statut', models.CharField(choices=[('INITIEE', 'Initiée'), ('ATTENTE', 'En attente de confirmation'), ('CONFIRMEE', 'Confirmée'), ('ECHOUEE', 'Échouée'), ('EXPIREE', 'Expirée'), ('ANNULEE', 'Annulée')], default='INITIEE', max_length=10)),
                ('code_confirmation', models.CharField(blank=True, max_length=6)),
                ('tentatives', models.PositiveSmallIntegerField(default=0)),
                ('date_initiation', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField()),
                ('date_confirmation', models.DateTimeField(blank=True, null=True)),
                ('motif_echec', models.CharField(blank=True, max_length=255)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_mobile', to='finance.facture')),
            ],
            options={
                'verbose_name': 'Transaction Mobile Money (simulation)',
                'verbose_name_plural': 'Transactions Mobile Money (simulation)',
                'ordering': ['-date_initiation'],
            },
        ),
    ]
