# Generated by Django 4.2.11 on 2026-07-02 07:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, verbose_name='Numéro du caveau')),
                ('rangee', models.PositiveIntegerField(verbose_name='Rangée')),
                ('colonne', models.PositiveIntegerField(verbose_name='Colonne')),
                ('localisation', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Coordonnées GPS')),
                ('statut', models.CharField(choices=[('DISPO', 'Disponible'), ('RESERVE', 'Réservé'), ('OCCUPE', 'Occupé / Validé'), ('NON_EXP', 'Non exploitable'), ('MAINT', 'En maintenance')], default='DISPO', max_length=10, verbose_name='Statut')),
                ('longueur_m', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('largeur_m', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('profondeur_m', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Caveau',
                'verbose_name_plural': 'Caveaux',
                'ordering': ['bloc', 'rangee', 'colonne'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCaveau',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, verbose_name='Numéro du caveau')),
                ('rangee', models.PositiveIntegerField(verbose_name='Rangée')),
                ('colonne', models.PositiveIntegerField(verbose_name='Colonne')),
                ('localisation', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Coordonnées GPS')),
                ('statut', models.CharField(choices=[('DISPO', 'Disponible'), ('RESERVE', 'Réservé'), ('OCCUPE', 'Occupé / Validé'), ('NON_EXP', 'Non exploitable'), ('MAINT', 'En maintenance')], default='DISPO', max_length=10, verbose_name='Statut')),
                ('longueur_m', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('largeur_m', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('profondeur_m', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('date_creation', models.DateTimeField(blank=True, editable=False)),
                ('date_modification', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Caveau',
                'verbose_name_plural': 'historical Caveaux',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='JournalModificationCaveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_statut', models.CharField(max_length=10)),
                ('nouveau_statut', models.CharField(max_length=10)),
                ('raison', models.TextField(blank=True)),
                ('horodatage', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('caveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal', to='cartographie.caveau')),
            ],
            options={
                'verbose_name': 'Journal modification caveau',
                'verbose_name_plural': 'Journal modifications caveaux',
                'ordering': ['-horodatage'],
                'managed': True,
            },
        ),
    ]
