# Generated by Django 4.2.11 on 2026-07-02 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cartographie', '0001_initial'),
        ('terrain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalmodificationcaveau',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcaveau',
            name='bloc',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='terrain.bloc'),
        ),
        migrations.AddField(
            model_name='historicalcaveau',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caveau',
            name='bloc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caveaux', to='terrain.bloc'),
        ),
        migrations.AlterUniqueTogether(
            name='caveau',
            unique_together={('bloc', 'rangee', 'colonne')},
        ),
    ]
