# Generated by Django 4.2.11 on 2026-07-02 07:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('nombre_rangees', models.PositiveIntegerField(default=1)),
                ('nombre_colonnes', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Bloc',
                'verbose_name_plural': 'Blocs',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Cimetiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du cimetière')),
                ('adresse', models.TextField(verbose_name='Adresse complète')),
                ('ville', models.CharField(max_length=100)),
                ('superficie_totale_m2', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Superficie totale (m²)')),
                ('tombeau_longueur_m', models.DecimalField(decimal_places=2, default=2.5, max_digits=5, verbose_name='Longueur standard tombeau (m)')),
                ('tombeau_largeur_m', models.DecimalField(decimal_places=2, default=1.2, max_digits=5, verbose_name='Largeur standard tombeau (m)')),
                ('pourcentage_chemins', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='% surface chemins/non exploitable')),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email_contact', models.EmailField(blank=True, max_length=254)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cimetière',
                'verbose_name_plural': 'Cimetières',
            },
        ),
        migrations.CreateModel(
            name='HistoricalBloc',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('nombre_rangees', models.PositiveIntegerField(default=1)),
                ('nombre_colonnes', models.PositiveIntegerField(default=1)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Bloc',
                'verbose_name_plural': 'historical Blocs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCimetiere',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du cimetière')),
                ('adresse', models.TextField(verbose_name='Adresse complète')),
                ('ville', models.CharField(max_length=100)),
                ('superficie_totale_m2', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Superficie totale (m²)')),
                ('tombeau_longueur_m', models.DecimalField(decimal_places=2, default=2.5, max_digits=5, verbose_name='Longueur standard tombeau (m)')),
                ('tombeau_largeur_m', models.DecimalField(decimal_places=2, default=1.2, max_digits=5, verbose_name='Largeur standard tombeau (m)')),
                ('pourcentage_chemins', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='% surface chemins/non exploitable')),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email_contact', models.EmailField(blank=True, max_length=254)),
                ('date_creation', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Cimetière',
                'verbose_name_plural': 'historical Cimetières',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la zone')),
                ('code', models.CharField(max_length=10, verbose_name='Code zone (ex: A, B, C)')),
                ('type_zone', models.CharField(choices=[('EXPLOIT', 'Exploitable'), ('CHEMIN', 'Chemin / Allée'), ('TECH', 'Zone technique'), ('ADMIN', 'Zone administrative'), ('NON_EXP', 'Non exploitable')], default='EXPLOIT', max_length=10)),
                ('superficie_m2', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True)),
                ('ordre_affichage', models.PositiveIntegerField(default=0)),
                ('cimetiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='terrain.cimetiere')),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
                'ordering': ['ordre_affichage', 'code'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalZone',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la zone')),
                ('code', models.CharField(max_length=10, verbose_name='Code zone (ex: A, B, C)')),
                ('type_zone', models.CharField(choices=[('EXPLOIT', 'Exploitable'), ('CHEMIN', 'Chemin / Allée'), ('TECH', 'Zone technique'), ('ADMIN', 'Zone administrative'), ('NON_EXP', 'Non exploitable')], default='EXPLOIT', max_length=10)),
                ('superficie_m2', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True)),
                ('ordre_affichage', models.PositiveIntegerField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cimetiere', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='terrain.cimetiere')),
            ],
            options={
                'verbose_name': 'historical Zone',
                'verbose_name_plural': 'historical Zones',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
