# Generated by Django 4.2.11 on 2026-07-02 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('terrain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalzone',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcimetiere',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalbloc',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalbloc',
            name='zone',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='terrain.zone'),
        ),
        migrations.AddField(
            model_name='bloc',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocs', to='terrain.zone'),
        ),
        migrations.AlterUniqueTogether(
            name='zone',
            unique_together={('cimetiere', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='bloc',
            unique_together={('zone', 'code')},
        ),
    ]
