# Generated by Django 4.2.11 on 2026-07-02 07:50

from django.db import migrations, models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrat', models.CharField(max_length=20, unique=True)),
                ('type_concession', models.CharField(choices=[('TEMP_5', 'Temporaire — 5 ans'), ('TEMP_10', 'Temporaire — 10 ans'), ('TEMP_15', 'Temporaire — 15 ans'), ('PERP', 'Perpétuelle'), ('FAM', 'Familiale')], max_length=10)),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIREE', 'Expirée'), ('RESILIEE', 'Résiliée'), ('RENOUVELEE', 'Renouvelée'), ('ALERTE', "En alerte d'expiration")], default='ACTIVE', max_length=10)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('date_signature', models.DateTimeField(auto_now_add=True)),
                ('date_dernier_renouvellement', models.DateField(blank=True, null=True)),
                ('contrat_pdf', models.FileField(blank=True, null=True, upload_to='documents/contrats/')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Concession',
                'verbose_name_plural': 'Concessions',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Exhumation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_demande', models.CharField(max_length=20, unique=True)),
                ('statut', models.CharField(choices=[('DEMANDE', 'Demande soumise'), ('INSTRUCT', 'En instruction'), ('AUTORISEE', 'Autorisée'), ('REALISEE', 'Réalisée'), ('REFUSEE', 'Refusée')], default='DEMANDE', max_length=10)),
                ('motif', models.TextField(verbose_name="Motif de l'exhumation")),
                ('destination_restes', models.TextField(blank=True, verbose_name='Destination des restes mortels')),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_autorisation', models.DateTimeField(blank=True, null=True)),
                ('date_realisation', models.DateField(blank=True, null=True)),
                ('motif_refus', models.TextField(blank=True)),
                ('autorisation_pdf', models.FileField(blank=True, null=True, upload_to='documents/exhumations/autorisations/', verbose_name="Autorisation d'exhumation (PDF)")),
                ('proces_verbal_pdf', models.FileField(blank=True, null=True, upload_to='documents/exhumations/pv/', verbose_name='Procès-verbal (PDF)')),
            ],
            options={
                'verbose_name': 'Exhumation',
                'verbose_name_plural': 'Exhumations',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalConcession',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('numero_contrat', models.CharField(db_index=True, max_length=20)),
                ('type_concession', models.CharField(choices=[('TEMP_5', 'Temporaire — 5 ans'), ('TEMP_10', 'Temporaire — 10 ans'), ('TEMP_15', 'Temporaire — 15 ans'), ('PERP', 'Perpétuelle'), ('FAM', 'Familiale')], max_length=10)),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIREE', 'Expirée'), ('RESILIEE', 'Résiliée'), ('RENOUVELEE', 'Renouvelée'), ('ALERTE', "En alerte d'expiration")], default='ACTIVE', max_length=10)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('date_signature', models.DateTimeField(blank=True, editable=False)),
                ('date_dernier_renouvellement', models.DateField(blank=True, null=True)),
                ('contrat_pdf', models.TextField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Concession',
                'verbose_name_plural': 'historical Concessions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalExhumation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('numero_demande', models.CharField(db_index=True, max_length=20)),
                ('statut', models.CharField(choices=[('DEMANDE', 'Demande soumise'), ('INSTRUCT', 'En instruction'), ('AUTORISEE', 'Autorisée'), ('REALISEE', 'Réalisée'), ('REFUSEE', 'Refusée')], default='DEMANDE', max_length=10)),
                ('motif', models.TextField(verbose_name="Motif de l'exhumation")),
                ('destination_restes', models.TextField(blank=True, verbose_name='Destination des restes mortels')),
                ('date_demande', models.DateTimeField(blank=True, editable=False)),
                ('date_autorisation', models.DateTimeField(blank=True, null=True)),
                ('date_realisation', models.DateField(blank=True, null=True)),
                ('motif_refus', models.TextField(blank=True)),
                ('autorisation_pdf', models.TextField(blank=True, max_length=100, null=True, verbose_name="Autorisation d'exhumation (PDF)")),
                ('proces_verbal_pdf', models.TextField(blank=True, max_length=100, null=True, verbose_name='Procès-verbal (PDF)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Exhumation',
                'verbose_name_plural': 'historical Exhumations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
