# Generated by Django 4.2.11 on 2026-07-02 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('concessions', '0001_initial'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalexhumation',
            name='autorisee_par',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalexhumation',
            name='concession',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='concessions.concession'),
        ),
        migrations.AddField(
            model_name='historicalexhumation',
            name='demandeur',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalexhumation',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalconcession',
            name='concession_precedente',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='concessions.concession'),
        ),
        migrations.AddField(
            model_name='historicalconcession',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalconcession',
            name='reservation',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='reservations.reservation'),
        ),
        migrations.AddField(
            model_name='historicalconcession',
            name='titulaire',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exhumation',
            name='autorisee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exhumations_autorisees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exhumation',
            name='concession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exhumations', to='concessions.concession'),
        ),
        migrations.AddField(
            model_name='exhumation',
            name='demandeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_exhumation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='concession',
            name='concession_precedente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renouvellements', to='concessions.concession'),
        ),
        migrations.AddField(
            model_name='concession',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='concession', to='reservations.reservation'),
        ),
        migrations.AddField(
            model_name='concession',
            name='titulaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='concessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
