# Generated by Django 4.2.11 on 2026-07-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('MFA', 'Code MFA'), ('NEW_RES', 'Nouvelle réservation (admin)'), ('CONF_RES', 'Confirmation réservation (client)'), ('VAL_RES', 'Réservation validée (client)'), ('REJ_RES', 'Réservation rejetée (client)'), ('FACT_EMISE', 'Facture émise'), ('RETARD', 'Retard de paiement'), ('EXPIRE', 'Alerte expiration concession'), ('EXPIREE', 'Concession expirée'), ('SEUIL', 'Seuil places critiques'), ('EXH_NEW', 'Nouvelle demande exhumation'), ('EXH_OK', 'Exhumation autorisée')], max_length=15)),
                ('statut', models.CharField(choices=[('PENDING', 'En attente'), ('SENT', 'Envoyée'), ('FAILED', 'Échec'), ('RETRY', 'Nouvelle tentative')], default='PENDING', max_length=10)),
                ('sujet', models.CharField(max_length=255)),
                ('corps_html', models.TextField()),
                ('corps_texte', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('tentatives', models.PositiveSmallIntegerField(default=0)),
                ('erreur', models.TextField(blank=True)),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
            },
        ),
    ]
